In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("IN_Trending.csv")

In [3]:
df.head()

,video_id,trending_date,title,channel_title,views,likes,dislikes,publish_time,category_id,tags,comments,channel_id,description
0,iAtoZar5W58,26.26.02,Aaya Sher - Lyrical | The Paradise | Nani | An...,Saregama Telugu,21242383,836273,0,2026-02-24T14:44:06Z,10,Anirudh Ravichander|The Paradise Theme OST|The...,24917,UC68nKdrLbLL0Vj7ilVkLmmg,"For more latest songs & videos, subscribe 👉 ht..."
1,BCQwSlYlEe8,26.26.02,Thaai Kizhavi - Official Trailer | Radikaa Sar...,Saregama Tamil,1913244,43317,0,2026-02-23T11:30:09Z,1,Maatikitaan Minorkunju|Maatikitaan Minorkunju ...,1181,UCzee67JnEcuvjErRyWP3GpQ,"For more latest songs & videos, subscribe 👉 ht..."
2,tVDiaaVkfNw,26.26.02,"Minecraft, But Every Mob in Chest!",Carry Depie,463090,9151,0,2026-02-26T09:01:45Z,20,carry depie|minecraft,434,UClqifC6Nd7v-IfTqce4k62A,in this video every mob become chest in minecr...
3,DBC2461TQbQ,26.26.02,"#Video - चोली के समान - #Ashish Yadav, Khushi ...",Aashish Yadav Entertainment,699235,60368,0,2026-02-26T00:30:09Z,10,Ashish Yadav|चोली के समान|Khushi Kakkar|ashish...,6468,UCjaOWpDTaZKe63ApNJ8BLPg,►Album :- चोली के समान ►Song :- Choli Ke Saman...
4,qj0TyXhGaLw,26.26.02,3000 Crore Plan Dhurandhar 2 Secret Deal | Dee...,Filmi Indian,232987,11738,0,2026-02-25T09:16:32Z,24,dhurandhar 2|dhurandhar 2 trailer|dhurandhar|d...,1065,UCeiAKuJGZrIjYvaq0nMwbJg,3000 Crore Plan Dhurandhar 2 Secret Deal Expla...

In [4]:
df.tail()

,video_id,trending_date,title,channel_title,views,likes,dislikes,publish_time,category_id,tags,comments,channel_id,description
16194,8vnzBO2U9R8,26.26.02,Maare Maai Baap Ke Karejawa Mein Chhuriya I मा...,B4U Bhojpuri,37444,87,0,2026-02-13T03:30:12Z,1,jaisi karni waisi bharni|bhojpuri video|bhojpu...,2,UCIobY5Y-ly9Bo458yjy36OQ,#manibhattachariya #meghashree #ayazkhan #prem...
16195,rRmkxXY9kXQ,26.26.02,HUM HAIEN JETHANI I हम हई जेठानी-Part-05 | RAN...,B4U Bhojpuri,29826,90,0,2026-02-12T12:31:12Z,1,hum hai jethani|hum haien jethani|rani chatter...,2,UCIobY5Y-ly9Bo458yjy36OQ,#ranichatterjee #khushijha #sonalimishra #ayaz...
16196,elzjjoy8kf8,26.26.02,"“कलेक्टर साहिबा “ 14 फ़रवरी ,शनिवार सुबह 8 बजे...",B4U Bhojpuri,54947,623,0,2026-02-12T07:07:40Z,1,[none],7,UCIobY5Y-ly9Bo458yjy36OQ,@sanjanapandey00 @ursgauravjha @santoshsrivast...
16197,kj0yf2lP3-Y,26.26.02,SAAHEB SE CHAPRASI HO GAYINI I साहेब से चपर...,B4U Bhojpuri,242429,570,0,2026-02-12T03:30:39Z,1,collector sahab gaane|collector sahab songs|co...,10,UCIobY5Y-ly9Bo458yjy36OQ,#sanjanapandey #gauravjha #omjha #pyarelalyad...
16198,G7XSYRCVA10,26.26.02,HUM HAIEN JETHANI I हम हई जेठानी-Part-04 | RAN...,B4U Bhojpuri,59187,172,0,2026-02-11T13:16:05Z,1,hum hai jethani|hum haien jethani|rani chatter...,3,UCIobY5Y-ly9Bo458yjy36OQ,#ranichatterjee #khushijha #sonalimishra #ayaz...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16199 entries, 0 to 16198
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   video_id       16199 non-null  object
 1   trending_date  16199 non-null  object
 2   title          16199 non-null  object
 3   channel_title  16199 non-null  object
 4   views          16199 non-null  int64
 5   likes          16199 non-null  int64
 6   dislikes       16199 non-null  int64
 7   publish_time   16199 non-null  object
 8   category_id    16199 non-null  int64
 9   tags           16199 non-null  object
 10  comments       16199 non-null  int64
 11  channel_id     16199 non-null  object
 12  description    14852 non-null  object
dtypes: int64(5), object(8)
memory usage: 1.6+ MB

In [7]:
df['publish_time']   = pd.to_datetime(df['publish_time'])
df['trending_date']  = pd.to_datetime(df['trending_date'], format='%y.%d.%m', errors='coerce')

In [8]:
df.head()

,video_id,trending_date,title,channel_title,views,likes,dislikes,publish_time,category_id,tags,comments,channel_id,description
0,iAtoZar5W58,2026-02-26,Aaya Sher - Lyrical | The Paradise | Nani | An...,Saregama Telugu,21242383,836273,0,2026-02-24 14:44:06+00:00,10,Anirudh Ravichander|The Paradise Theme OST|The...,24917,UC68nKdrLbLL0Vj7ilVkLmmg,"For more latest songs & videos, subscribe 👉 ht..."
1,BCQwSlYlEe8,2026-02-26,Thaai Kizhavi - Official Trailer | Radikaa Sar...,Saregama Tamil,1913244,43317,0,2026-02-23 11:30:09+00:00,1,Maatikitaan Minorkunju|Maatikitaan Minorkunju ...,1181,UCzee67JnEcuvjErRyWP3GpQ,"For more latest songs & videos, subscribe 👉 ht..."
2,tVDiaaVkfNw,2026-02-26,"Minecraft, But Every Mob in Chest!",Carry Depie,463090,9151,0,2026-02-26 09:01:45+00:00,20,carry depie|minecraft,434,UClqifC6Nd7v-IfTqce4k62A,in this video every mob become chest in minecr...
3,DBC2461TQbQ,2026-02-26,"#Video - चोली के समान - #Ashish Yadav, Khushi ...",Aashish Yadav Entertainment,699235,60368,0,2026-02-26 00:30:09+00:00,10,Ashish Yadav|चोली के समान|Khushi Kakkar|ashish...,6468,UCjaOWpDTaZKe63ApNJ8BLPg,►Album :- चोली के समान ►Song :- Choli Ke Saman...
4,qj0TyXhGaLw,2026-02-26,3000 Crore Plan Dhurandhar 2 Secret Deal | Dee...,Filmi Indian,232987,11738,0,2026-02-25 09:16:32+00:00,24,dhurandhar 2|dhurandhar 2 trailer|dhurandhar|d...,1065,UCeiAKuJGZrIjYvaq0nMwbJg,3000 Crore Plan Dhurandhar 2 Secret Deal Expla...

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16199 entries, 0 to 16198
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   video_id       16199 non-null  object
 1   trending_date  16199 non-null  datetime64[ns]
 2   title          16199 non-null  object
 3   channel_title  16199 non-null  object
 4   views          16199 non-null  int64
 5   likes          16199 non-null  int64
 6   dislikes       16199 non-null  int64
 7   publish_time   16199 non-null  datetime64[ns, UTC]
 8   category_id    16199 non-null  int64
 9   tags           16199 non-null  object
 10  comments       16199 non-null  int64
 11  channel_id     16199 non-null  object
 12  description    14852 non-null  object
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), int64(5), object(6)
memory usage: 1.6+ MB

In [10]:
df.shape

(16199, 13)

In [12]:
df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'views', 'likes',
       'dislikes', 'publish_time', 'category_id', 'tags', 'comments',
       'channel_id', 'description'],
      dtype='object')

In [13]:
df.isnull().sum()

video_id            0
trending_date       0
title               0
channel_title       0
views               0
likes               0
dislikes            0
publish_time        0
category_id         0
tags                0
comments            0
channel_id          0
description      1347
dtype: int64

In [14]:
df['description'] = df['description'].fillna('No Description')

In [15]:
df.isnull().sum()

video_id         0
trending_date    0
title            0
channel_title    0
views            0
likes            0
dislikes         0
publish_time     0
category_id      0
tags             0
comments         0
channel_id       0
description      0
dtype: int64

In [17]:
df[df.duplicated()]

Empty DataFrame
Columns: [video_id, trending_date, title, channel_title, views, likes, dislikes, publish_time, category_id, tags, comments, channel_id, description]
Index: []

In [18]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\ghosh\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\ghosh\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\ghosh\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ghosh\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"       # default user
password = "12345678"       # the password you set during installation
host = "localhost"          # if running locally
port = "5432"               # default PostgreSQL port
database = "Youtube trending analysis"  # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#Step 2: Load DataFrame into PostgreSQL
table_name = "youtube"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'youtube' in database 'Youtube trending analysis'.